project:
  type: website
  output-dir: docs

website:
  title: "ppol5202_web_tutorial_msno"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - posts/msno_tut.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



